// generated by BIFF8 Record List Parser

#include "biff8_records.h"
#include <stdio.h>

void biff8RecordNamePrint(int record)
{
	switch(record)
	{
	case BIFF8_RECORD_FORMULA:
		printf("FORMULA (0x0006)\n");
		break;
	case BIFF8_RECORD_EOF:
		printf("EOF (0x000a)\n");
		break;
	case BIFF8_RECORD_CALCCOUNT:
		printf("CALCCOUNT (0x000c)\n");
		break;
	case BIFF8_RECORD_CALCMODE:
		printf("CALCMODE (0x000d)\n");
		break;
	case BIFF8_RECORD_PRECISION:
		printf("PRECISION (0x000e)\n");
		break;
	case BIFF8_RECORD_REFMODE:
		printf("REFMODE (0x000f)\n");
		break;
	case BIFF8_RECORD_DELTA:
		printf("DELTA (0x0010)\n");
		break;
	case BIFF8_RECORD_ITERATION:
		printf("ITERATION (0x0011)\n");
		break;
	case BIFF8_RECORD_PROTECT:
		printf("PROTECT (0x0012)\n");
		break;
	case BIFF8_RECORD_PASSWORD:
		printf("PASSWORD (0x0013)\n");
		break;
	case BIFF8_RECORD_HEADER:
		printf("HEADER (0x0014)\n");
		break;
	case BIFF8_RECORD_FOOTER:
		printf("FOOTER (0x0015)\n");
		break;
	case BIFF8_RECORD_EXTERNSHEET:
		printf("EXTERNSHEET (0x0017)\n");
		break;
	case BIFF8_RECORD_DEFINEDNAME:
		printf("DEFINEDNAME (0x0018)\n");
		break;
	case BIFF8_RECORD_WINDOWPROTECT:
		printf("WINDOWPROTECT (0x0019)\n");
		break;
	case BIFF8_RECORD_VERTICALPAGEBREAKS:
		printf("VERTICALPAGEBREAKS (0x001a)\n");
		break;
	case BIFF8_RECORD_HORIZONTALPAGEBREAKS:
		printf("HORIZONTALPAGEBREAKS (0x001b)\n");
		break;
	case BIFF8_RECORD_NOTE:
		printf("NOTE (0x001c)\n");
		break;
	case BIFF8_RECORD_SELECTION:
		printf("SELECTION (0x001d)\n");
		break;
	case BIFF8_RECORD_DATEMODE:
		printf("DATEMODE (0x0022)\n");
		break;
	case BIFF8_RECORD_EXTERNALNAME:
		printf("EXTERNALNAME (0x0023)\n");
		break;
	case BIFF8_RECORD_LEFTMARGIN:
		printf("LEFTMARGIN (0x0026)\n");
		break;
	case BIFF8_RECORD_RIGHTMARGIN:
		printf("RIGHTMARGIN (0x0027)\n");
		break;
	case BIFF8_RECORD_TOPMARGIN:
		printf("TOPMARGIN (0x0028)\n");
		break;
	case BIFF8_RECORD_BOTTOMMARGIN:
		printf("BOTTOMMARGIN (0x0029)\n");
		break;
	case BIFF8_RECORD_PRINTHEADERS:
		printf("PRINTHEADERS (0x002a)\n");
		break;
	case BIFF8_RECORD_PRINTGRIDLINES:
		printf("PRINTGRIDLINES (0x002b)\n");
		break;
	case BIFF8_RECORD_FILEPASS:
		printf("FILEPASS (0x002f)\n");
		break;
	case BIFF8_RECORD_FONT:
		printf("FONT (0x0031)\n");
		break;
	case BIFF8_RECORD_CONTINUE:
		printf("CONTINUE (0x003c)\n");
		break;
	case BIFF8_RECORD_WINDOW1:
		printf("WINDOW1 (0x003d)\n");
		break;
	case BIFF8_RECORD_BACKUP:
		printf("BACKUP (0x0040)\n");
		break;
	case BIFF8_RECORD_PANE:
		printf("PANE (0x0041)\n");
		break;
	case BIFF8_RECORD_CODEPAGE:
		printf("CODEPAGE (0x0042)\n");
		break;
	case BIFF8_RECORD_PLS:
		printf("PLS (0x004d)\n");
		break;
	case BIFF8_RECORD_DCONREF:
		printf("DCONREF (0x0051)\n");
		break;
	case BIFF8_RECORD_DEFCOLWIDTH:
		printf("DEFCOLWIDTH (0x0055)\n");
		break;
	case BIFF8_RECORD_XCT:
		printf("XCT (0x0059)\n");
		break;
	case BIFF8_RECORD_CRN:
		printf("CRN (0x005a)\n");
		break;
	case BIFF8_RECORD_FILESHARING:
		printf("FILESHARING (0x005b)\n");
		break;
	case BIFF8_RECORD_WRITEACCESS:
		printf("WRITEACCESS (0x005c)\n");
		break;
	case BIFF8_RECORD_UNCALCED:
		printf("UNCALCED (0x005e)\n");
		break;
	case BIFF8_RECORD_SAVERECALC:
		printf("SAVERECALC (0x005f)\n");
		break;
	case BIFF8_RECORD_OBJECTPROTECT:
		printf("OBJECTPROTECT (0x0063)\n");
		break;
	case BIFF8_RECORD_COLINFO:
		printf("COLINFO (0x007d)\n");
		break;
	case BIFF8_RECORD_GUTS:
		printf("GUTS (0x0080)\n");
		break;
	case BIFF8_RECORD_SHEETPR:
		printf("SHEETPR (0x0081)\n");
		break;
	case BIFF8_RECORD_GRIDSET:
		printf("GRIDSET (0x0082)\n");
		break;
	case BIFF8_RECORD_HCENTER:
		printf("HCENTER (0x0083)\n");
		break;
	case BIFF8_RECORD_VCENTER:
		printf("VCENTER (0x0084)\n");
		break;
	case BIFF8_RECORD_SHEET:
		printf("SHEET (0x0085)\n");
		break;
	case BIFF8_RECORD_WRITEPROT:
		printf("WRITEPROT (0x0086)\n");
		break;
	case BIFF8_RECORD_COUNTRY:
		printf("COUNTRY (0x008c)\n");
		break;
	case BIFF8_RECORD_HIDEOBJ:
		printf("HIDEOBJ (0x008d)\n");
		break;
	case BIFF8_RECORD_SORT:
		printf("SORT (0x0090)\n");
		break;
	case BIFF8_RECORD_PALETTE:
		printf("PALETTE (0x0092)\n");
		break;
	case BIFF8_RECORD_STANDARDWIDTH:
		printf("STANDARDWIDTH (0x0099)\n");
		break;
	case BIFF8_RECORD_SCL:
		printf("SCL (0x00a0)\n");
		break;
	case BIFF8_RECORD_PAGESETUP:
		printf("PAGESETUP (0x00a1)\n");
		break;
	case BIFF8_RECORD_MULRK:
		printf("MULRK (0x00bd)\n");
		break;
	case BIFF8_RECORD_MULBLANK:
		printf("MULBLANK (0x00be)\n");
		break;
	case BIFF8_RECORD_RSTRING:
		printf("RSTRING (0x00d6)\n");
		break;
	case BIFF8_RECORD_DBCELL:
		printf("DBCELL (0x00d7)\n");
		break;
	case BIFF8_RECORD_BOOKBOOL:
		printf("BOOKBOOL (0x00da)\n");
		break;
	case BIFF8_RECORD_SCENPROTECT:
		printf("SCENPROTECT (0x00dd)\n");
		break;
	case BIFF8_RECORD_XF:
		printf("XF (0x00e0)\n");
		break;
	case BIFF8_RECORD_MERGEDCELLS:
		printf("MERGEDCELLS (0x00e5)\n");
		break;
	case BIFF8_RECORD_BITMAP:
		printf("BITMAP (0x00e9)\n");
		break;
	case BIFF8_RECORD_PHONETICPR:
		printf("PHONETICPR (0x00ef)\n");
		break;
	case BIFF8_RECORD_SST:
		printf("SST (0x00fc)\n");
		break;
	case BIFF8_RECORD_LABELSST:
		printf("LABELSST (0x00fd)\n");
		break;
	case BIFF8_RECORD_EXTSST:
		printf("EXTSST (0x00ff)\n");
		break;
	case BIFF8_RECORD_LABELRANGES:
		printf("LABELRANGES (0x015f)\n");
		break;
	case BIFF8_RECORD_USESELFS:
		printf("USESELFS (0x0160)\n");
		break;
	case BIFF8_RECORD_DSF:
		printf("DSF (0x0161)\n");
		break;
	case BIFF8_RECORD_EXTERNALBOOK:
		printf("EXTERNALBOOK (0x01ae)\n");
		break;
	case BIFF8_RECORD_CFHEADER:
		printf("CFHEADER (0x01b0)\n");
		break;
	case BIFF8_RECORD_DATAVALIDATIONS:
		printf("DATAVALIDATIONS (0x01b2)\n");
		break;
	case BIFF8_RECORD_HYPERLINK:
		printf("HYPERLINK (0x01b8)\n");
		break;
	case BIFF8_RECORD_DATAVALIDATION:
		printf("DATAVALIDATION (0x01be)\n");
		break;
	case BIFF8_RECORD_DIMENSION:
		printf("DIMENSION (0x0200)\n");
		break;
	case BIFF8_RECORD_BLANK:
		printf("BLANK (0x0201)\n");
		break;
	case BIFF8_RECORD_NUMBER:
		printf("NUMBER (0x0203)\n");
		break;
	case BIFF8_RECORD_LABEL:
		printf("LABEL (0x0204)\n");
		break;
	case BIFF8_RECORD_BOOLERR:
		printf("BOOLERR (0x0205)\n");
		break;
	case BIFF8_RECORD_STRING:
		printf("STRING (0x0207)\n");
		break;
	case BIFF8_RECORD_ROW:
		printf("ROW (0x0208)\n");
		break;
	case BIFF8_RECORD_INDEX:
		printf("INDEX (0x020b)\n");
		break;
	case BIFF8_RECORD_ARRAY:
		printf("ARRAY (0x0221)\n");
		break;
	case BIFF8_RECORD_DEFAULTROWHEIGHT:
		printf("DEFAULTROWHEIGHT (0x0225)\n");
		break;
	case BIFF8_RECORD_DATATABLE:
		printf("DATATABLE (0x0236)\n");
		break;
	case BIFF8_RECORD_WINDOW2:
		printf("WINDOW2 (0x023e)\n");
		break;
	case BIFF8_RECORD_RK:
		printf("RK (0x027e)\n");
		break;
	case BIFF8_RECORD_STYLE:
		printf("STYLE (0x0293)\n");
		break;
	case BIFF8_RECORD_FORMAT:
		printf("FORMAT (0x041e)\n");
		break;
	case BIFF8_RECORD_SHAREDFMLA:
		printf("SHAREDFMLA (0x04bc)\n");
		break;
	case BIFF8_RECORD_QUICKTIP:
		printf("QUICKTIP (0x0800)\n");
		break;
	case BIFF8_RECORD_BOF:
		printf("BOF (0x0809)\n");
		break;
	case BIFF8_RECORD_SHEETLAYOUT:
		printf("SHEETLAYOUT (0x0862)\n");
		break;
	case BIFF8_RECORD_SHEETPROTECTION:
		printf("SHEETPROTECTION (0x0867)\n");
		break;
	case BIFF8_RECORD_RANGEPROTECTION:
		printf("RANGEPROTECTION (0x0868)\n");
		break;
	default:
		printf("(0x%.4x): unknown record!\n", record);
		break;
	}
}
