/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2013 Billy Millare
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * biff_record_list_parser.c
 *
 *  Created on: Jun 20, 2011
 *      Author: Billy
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define INFO	"// generated by BIFF Record List Parser\n\n"

#define BIFF_RECORD "BIFF_RECORD"
#define BIFF_RECORD_LIST "BIFF_RECORD_LIST"

#define RECORD_LIST		"BIFFRecordList"

#define BY_RECORD		RECORD_LIST"_record"
#define IFILE_BY_RECORD 	BY_RECORD".txt"
#define OFILE_BY_RECORD_H		BY_RECORD".h"

#define BY_NUMBER		RECORD_LIST"_number"
#define IFILE_BY_NUMBER		BY_NUMBER".txt"
#define OFILE_BY_NUMBER_H		BY_NUMBER".h"

#define OFILE_C	RECORD_LIST".c"

#define COMPILE_SWITCH		"_BIFFRECORDLIST_H"

#define FUNCTION_ARG "record"
#define FUNCTION	"void BIFFRecordNamePrint(int "FUNCTION_ARG")"

static void parse(const char *list, const char *output_h, const char *output_c, int record_first)
{
	FILE *ifile = fopen(list, "r");
	
	if(!ifile)
	{
		printf("ERROR: cannot open/read file, %s.\n", list);
		exit(1);
	}

	FILE *ofile_h = fopen(output_h, "w");

	if(!ofile_h)
	{
		fclose(ifile);
		printf("ERROR: cannot open/write file, %s.\n", output_h);
		exit(1);
	}
	
	FILE *ofile_c = 0;
	
	if(output_c)
	{
		if(!(ofile_c = fopen(output_c, "w")))
		{
			fclose(ifile);
			fclose(ofile_h);
			printf("ERROR: cannot open/write file, %s.\n", output_c);
			exit(1);
		}
	}

	char record[500];
	char description[1000];
	int number;

	int not_finished = 2;
	int i, c;

	fprintf(ofile_h, INFO);
	
	fprintf(ofile_h, "#ifndef "COMPILE_SWITCH"\n");
	fprintf(ofile_h, "#define "COMPILE_SWITCH"\n\n");
	
	fprintf(ofile_h, "typedef enum {\n");
	
	if(ofile_c)
	{
		fprintf(ofile_c, INFO);
		fprintf(ofile_c, "#include \"%s\"\n", output_h);
		fprintf(ofile_c, "#include <stdio.h>\n\n");
		fprintf(ofile_c, FUNCTION"\n{\n");
		fprintf(ofile_c, "\tswitch("FUNCTION_ARG")\n");
		fprintf(ofile_c, "\t{\n");
	}
	
	while(1)
	{
		if((record_first = !record_first))
		{
			if(fscanf(ifile, "%x", &number) == EOF)
				break;
			
			while((c = fgetc(ifile)) != EOF && c != '\n');

			if(c == EOF)
				break;
		}
		else
		{
			for(i = 0; (record[i] = fgetc(ifile)) != ':' && record[i] != EOF; i++);

			if(record[i] == EOF)
				break;

			record[i] = 0;

			if(!fgets(description, 999, ifile))
				break;
			
			if(description[strlen(description) - 1] == '\n')
				description[strlen(description) - 1] = 0;
		}
		if(!(--not_finished))
		{
			if(ofile_c)
			{
				fprintf(ofile_c, "\tcase "BIFF_RECORD"_%s:\n", record);
				fprintf(ofile_c, "\t\tprintf(\"%s (0x%.4x): %s\\n\");\n", record, number, description);
				fprintf(ofile_c, "\t\tbreak;\n");
			}
			
			fprintf(ofile_h, "\t"BIFF_RECORD"_%s\t\t= 0x%.4x,\t//%s\n", record, number, description);
			not_finished = 2;
		}
	}
	
	if(ofile_c)
	{
		fprintf(ofile_c, "\tdefault:\n");
		fprintf(ofile_c, "\t\tprintf(\"(0x%%.4x): unknown record!\\n\", "FUNCTION_ARG");\n");
		fprintf(ofile_c, "\t\tbreak;\n");
		
		fprintf(ofile_c, "\t}\n");
		fprintf(ofile_c, "}\n");
		fclose(ofile_c);
	}
	
	fprintf(ofile_h, "} " BIFF_RECORD_LIST";\n\n");
	fprintf(ofile_h, FUNCTION";\n\n");
	fprintf(ofile_h, "#endif // "COMPILE_SWITCH"\n");
	
	fclose(ifile);
	fclose(ofile_h);
}

int main(void)
{
	parse(IFILE_BY_RECORD, OFILE_BY_RECORD_H, OFILE_C, 1);
	parse(IFILE_BY_NUMBER, OFILE_BY_NUMBER_H, 0, 0);
	return 0;
}
