/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2013 Billy Millare
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * BIFF8RecordListParser.c
 *
 *  Created on: Jun 20, 2011
 *      Author: Billy
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define INFO "// generated by BIFF8 Record List Parser\n\n"

#define BIFF8_RECORD "BIFF8_RECORD"
#define BIFF8_RECORD_LIST "BIFF8_RECORD_LIST"

#define IFILE "BIFF8Records.txt"
#define OFILE_H "biff8_records.h"
#define OFILE_C "biff8_records.c"

#define COMPILE_SWITCH		"BIFF8_RECORDS_H_"

#define FUNCTION_ARG "record"
#define FUNCTION	"void biff8RecordNamePrint(int "FUNCTION_ARG")"

int main(void)
{
	FILE *ifile = fopen(IFILE, "r");
	
	if(!ifile)
	{
		printf("ERROR: cannot open/read file, %s.\n", IFILE);
		exit(1);
	}
	
	FILE *ofile_h = fopen(OFILE_H, "w");
	
	if(!ofile_h)
	{
		fclose(ifile);
		printf("ERROR: cannot open/write file, %s.\n", OFILE_H);
		exit(1);
	}
	
	FILE *ofile_c = fopen(OFILE_C, "w");
	
	if(!ofile_c)
	{
		fclose(ifile);
		fclose(ofile_h);
		printf("ERROR: cannot open/write file, %s.\n", OFILE_C);
		exit(1);
	}
	
	char record[50];
	int number;
	
	fprintf(ofile_h, INFO);
	fprintf(ofile_h, "#ifndef "COMPILE_SWITCH"\n");
	fprintf(ofile_h, "#define "COMPILE_SWITCH"\n\n");
	fprintf(ofile_h, "typedef enum {\n");
	
	fprintf(ofile_c, INFO);
	fprintf(ofile_c, "#include \"%s\"\n", OFILE_H);
	fprintf(ofile_c, "#include <stdio.h>\n\n");
	fprintf(ofile_c, FUNCTION"\n{\n");
	fprintf(ofile_c, "\tswitch("FUNCTION_ARG")\n");
	fprintf(ofile_c, "\t{\n");
	
	while(fscanf(ifile, "%x%*c%s%*c", &number, record) == 2)
	{
		fprintf(ofile_h, "\t"BIFF8_RECORD"_%s = 0x%.4x,\n", record, number);
		
		fprintf(ofile_c, "\tcase "BIFF8_RECORD"_%s:\n", record);
		fprintf(ofile_c, "\t\tprintf(\"%s (0x%.4x)\\n\");\n", record, number);
		fprintf(ofile_c, "\t\tbreak;\n");
	}
	
	fprintf(ofile_h, "} "BIFF8_RECORD_LIST";\n\n");
	fprintf(ofile_h, FUNCTION";\n\n");
	fprintf(ofile_h, "#endif // "COMPILE_SWITCH"\n");
	
	fprintf(ofile_c, "\tdefault:\n");
	fprintf(ofile_c, "\t\tprintf(\"(0x%%.4x): unknown record!\\n\", "FUNCTION_ARG");\n");
	fprintf(ofile_c, "\t\tbreak;\n");
	fprintf(ofile_c, "\t}\n");
	fprintf(ofile_c, "}\n");
	
	fclose(ofile_c);
	fclose(ofile_h);
	fclose(ifile);
	
	return 0;
}
